"""add redesign schema

Adds account, session, check-in, wallet transaction, and contact message tables, plus
optional gallery brand columns. Schema only; no API routes use these until Phase 3+.

Revision ID: 30b349769e87
Revises: c3a7f1d9e2b4
Create Date: 2026-06-29 22:28:21.653272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b349769e87'
down_revision: Union[str, Sequence[str], None] = 'c3a7f1d9e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_table('contact_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_message_received_at'), 'contact_message', ['received_at'], unique=False)
    op.create_table('check_in',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('point_awarded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_in_account_gallery_checked_in_at', 'check_in', ['account_id', 'gallery_id', 'checked_in_at'], unique=False)
    op.create_index(op.f('ix_check_in_account_id'), 'check_in', ['account_id'], unique=False)
    op.create_index(op.f('ix_check_in_gallery_id'), 'check_in', ['gallery_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_challenge_token', sa.String(length=255), nullable=True),
    sa.Column('check_in_challenge_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_challenge_gallery_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['check_in_challenge_gallery_id'], ['gallery.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_account_id'), 'session', ['account_id'], unique=False)
    op.create_index(op.f('ix_session_check_in_challenge_gallery_id'), 'session', ['check_in_challenge_gallery_id'], unique=False)
    op.create_index(op.f('ix_session_token_hash'), 'session', ['token_hash'], unique=True)
    op.create_table('wallet_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('check_in_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_in.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transaction_account_id'), 'wallet_transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_wallet_transaction_check_in_id'), 'wallet_transaction', ['check_in_id'], unique=True)
    op.add_column('gallery', sa.Column('brand_name', sa.String(length=255), nullable=True))
    op.add_column('gallery', sa.Column('brand_logo_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery', 'brand_logo_url')
    op.drop_column('gallery', 'brand_name')
    op.drop_index(op.f('ix_wallet_transaction_check_in_id'), table_name='wallet_transaction')
    op.drop_index(op.f('ix_wallet_transaction_account_id'), table_name='wallet_transaction')
    op.drop_table('wallet_transaction')
    op.drop_index(op.f('ix_session_token_hash'), table_name='session')
    op.drop_index(op.f('ix_session_check_in_challenge_gallery_id'), table_name='session')
    op.drop_index(op.f('ix_session_account_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_check_in_gallery_id'), table_name='check_in')
    op.drop_index(op.f('ix_check_in_account_id'), table_name='check_in')
    op.drop_index('ix_check_in_account_gallery_checked_in_at', table_name='check_in')
    op.drop_table('check_in')
    op.drop_index(op.f('ix_contact_message_received_at'), table_name='contact_message')
    op.drop_table('contact_message')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
