"""create gallery and feed_item tables

Revision ID: b130255744cd
Revises: 
Create Date: 2026-06-26 10:16:49.982653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b130255744cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formatted_address', sa.String(length=512), nullable=True),
    sa.Column('suburb', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_status', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('featured_rank', sa.Integer(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_slug'), 'gallery', ['slug'], unique=True)
    op.create_index(op.f('ix_gallery_suburb'), 'gallery', ['suburb'], unique=False)
    op.create_table('feed_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('gallery_id', sa.Uuid(), nullable=True),
    sa.Column('creative_name', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('location_text', sa.String(length=512), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('featured_rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_item_ends_on'), 'feed_item', ['ends_on'], unique=False)
    op.create_index(op.f('ix_feed_item_gallery_id'), 'feed_item', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_feed_item_slug'), 'feed_item', ['slug'], unique=True)
    op.create_index(op.f('ix_feed_item_starts_on'), 'feed_item', ['starts_on'], unique=False)
    op.create_table('gallery_external_ref',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_external_ref_source_external_id')
    )
    op.create_index(op.f('ix_gallery_external_ref_gallery_id'), 'gallery_external_ref', ['gallery_id'], unique=False)
    op.create_table('gallery_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('permission_status', sa.String(length=32), server_default='unconfirmed', nullable=False),
    sa.Column('attribution', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_rank', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_image_gallery_id'), 'gallery_image', ['gallery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_image_gallery_id'), table_name='gallery_image')
    op.drop_table('gallery_image')
    op.drop_index(op.f('ix_gallery_external_ref_gallery_id'), table_name='gallery_external_ref')
    op.drop_table('gallery_external_ref')
    op.drop_index(op.f('ix_feed_item_starts_on'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_slug'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_gallery_id'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_ends_on'), table_name='feed_item')
    op.drop_table('feed_item')
    op.drop_index(op.f('ix_gallery_suburb'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_slug'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###
